spring:
  datasource:
    url: &dbURL jdbc:postgresql://localhost:5432/company
    username: &dbUser postgres
    password: &dbPassword postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 9529
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file: "./application.log"
app:
  security:
    exptration_time: 100000